---  #oracle settings
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: c##scott
    password: tiger


--- #mybatis mapper xml
mybatis:
  mapper-locations: classpath:sqlmapper/*.xml
  configuration.map-underscore-to-camel-case: true