---  #oracle settings
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: c##scott
    password: tiger


--- #mybatis mapper xml
mybatis:
  mapper-locations: classpath:sql/*.xml
  configuration.map-underscore-to-camel-case: true
--- #upload/download
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:\\Users\\oujeo\\IdeaProjects\\reaceCRUDServer\\src\\main\\resources\\file